/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type Language = 'en' | 'km';

export const translations = {
  en: {
    appName: 'Transaction Tracker',
    appSubName: 'IndexedDB Engine',
    appDesc: 'Instantly extract structured data from pasted bank SMS texts with duplicate prevention',
    totalTransactions: 'Total Transactions',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    todaysIncome: "Today's Income",
    todaysInflow: "Current daily inflow",
    netCashFlow: 'Total Transactions',
    recordCount: 'Transaction Count',
    needsReview: 'Needs Review',
    todayLabel: 'Today',
    rangeLabel: 'Search Result',
    allTimeTotalLabel: 'Total in DB',
    inRangeLabel: 'Search Result',
    sourceOthers: 'Others',
    clearAllData: 'Clear All Data',
    placeholderPaste: 'Example:\n$999.99 paid by KHEAV CHINCHHAY AND HIS WIFE (*666) on Jun 12, 12:26 PM via ABA PAY at Brown Coffee by KCC. Remark: . Trx. ID: 178124197042803, APV: 612744.\n\nOr click "Load Sample Alerts" inside paste instructions above...',
    parseImport: 'Parse & Record',
    searchPlaceholder: 'Search transactions by name, ID, source...',
    typeAll: 'All Types',
    typeIncome: 'Income',
    typeExpense: 'Expense',
    typeUnknown: 'Unknown',
    reviewAll: 'All Review Status',
    reviewOk: 'Normal Records',
    reviewFlagged: 'Needs Review',
    exportCsv: 'Export CSV',
    exportExcel: 'Export Excel',
    exportJson: 'Export JSON',
    printReport: 'Print',
    thDate: 'Date & Time',
    thDetails: 'Merchant / Description',
    thAmount: 'Amount',
    thPayerPayee: 'Payer / Payee',
    thChannel: 'Channel / Source',
    thTrxId: 'Trx ID / APV',
    thActions: 'Actions',
    btnEdit: 'Edit',
    btnDelete: 'Delete',
    noTransactionsYet: 'No transactions listed. Try pasting a bank notification text above.',
    easySandboxTitle: 'Sandbox Clipboard Help:',
    easySandboxContent: "Don't have real messages at hand? Toggle the 'Show Sample Alerts Helper' instructions panel above to instantly grab standard ABA/Canadia test snippets!",
    toastClearSuccess: 'Database index cleared successfully.',
    toastClearFail: 'Failed to clear database.',
    toastDeleteSuccess: 'Transaction removed from history database.',
    toastDeleteFail: 'Failed to delete item from database.',
    toastImportSuccess: 'Successfully added {count} transaction(s).',
    toastImportDuplicate: '({count} duplicate(s) automatically skipped).',
    toastImportReview: '[{count} flagged for review]',
    modalClearTitle: 'Clear All Transaction History?',
    modalClearWarning: 'Are you absolutely sure you want to clear your entire local transaction history? This action is permanent and cannot be undone!',
    modalClearGoogleSheetsInfo: 'If you are connected to Google Sheets and want to keep your existing data in the sheet after clearing local records, please change the name of the sheet tab before importing new transactions. Clearing data in this system does not affect your Google Sheet unless you submit new transactions.',
    modalClearCancel: 'No, Keep My Data',
    modalClearConfirm: 'Yes, Clear Everything',
    modalPhraseTitle: 'Type Word to Confirm Deletion',
    modalPhrasePrompt: 'To confirm clearing all data, please type the confirmation phrase below (case-insensitive):',
    modalPhraseRequiredWord: 'I LOVE BONG CHHAY',
    modalPhrasePlaceholder: 'Type "I LOVE BONG CHHAY" here (any case)...',
    modalPhraseError: 'Please enter "I LOVE BONG CHHAY" correctly to proceed.',
    modalPhraseValid: 'Phrase matched! Click Confirm to permanently clear all data.',
    modalPhraseConfirmBtn: 'Confirm',
    modalPhraseCancelBtn: 'Cancel',
    modalDeleteTitle: 'Delete This Transaction?',
    modalDeleteWarning: 'Are you sure you want to permanently delete this transaction record from your local ledger history?',
    modalDeleteCancel: 'Cancel',
    modalDeleteConfirm: 'Permanently Delete',
    modalEditTitle: 'Edit Transaction Details',
    labelType: 'Transaction Type',
    labelAmount: 'Amount / Value',
    labelCurrency: 'Currency',
    labelDate: 'Date (e.g. Jun 12)',
    labelTime: 'Time (e.g. 12:26 PM)',
    labelMerchant: 'Merchant / Beneficiary',
    labelPayerPayee: 'Payer / Payee Details',
    labelChannel: 'Source Channel / Bank',
    labelTrxId: 'Transaction Trx. ID',
    labelApv: 'APV Auth Code',
    labelRemark: 'Remark / Note',
    labelRawText: 'Original Pasted Text',
    labelFlaggedReview: 'Flagged for Review / Unresolved fields',
    btnSave: 'Save Changes',
    btnCancel: 'Cancel',
    summaryInflow: 'Ready inflow',
    summaryOutflow: 'Incurred outflow',
    summarySaved: 'Saved items in index',
    summaryMissing: 'Missing amounts or fields',
    summaryNetDesc: 'Income minus expenses',
    filterHeading: 'Active Filter Options',
    sortByLabel: 'Sort By',
    sortOrderLabel: 'Order',
    sortDate: 'Date Time',
    sortAmount: 'Amount',
    sortCreated: 'Date Created',
    orderAsc: 'Ascending',
    orderDesc: 'Descending',
    allSources: 'All Sources',
    duplicateText: 'Duplicate',
    sampleAlertsTitle: 'Cambodian Bank SMS / Alert Snippets Samples',
    sampleAlertsDesc: 'You can copy any of these bilingual test messages and paste them into the box to test parsing capability.',
    clickToCopy: 'Click text block to copy',
    copiedText: 'Copied to clipboard!',
    howToUseTitle: 'SMS Fast Parser Instructions & Guide',
    step1: 'Copy your incoming push notification texts or SMS transaction messages from your mobile banking apps.',
    step2: 'Paste them into the text area above (you can paste multiple messages separated by empty lines).',
    step3: 'Click "Parse & Import". The system automatically isolates transactions, detects USD/KHR amounts, extracts Trx IDs/APV codes, checks for duplicity, and logs them securely in IndexedDB.',
    step4: 'Our smart system instantly auto-detects Income and Expense from pasted messages, and you can also record expenses or missing logs manually. Export to CSV/JSON, sync directly with Google Sheets, or edit anytime.',
    showSamplesBtn: 'Show Sample Alerts Helper',
    hideSamplesBtn: 'Hide Sample Alerts',
    filterByLabel: 'Filter by',
    sourceFilterPlaceholder: 'Source App',
    duplicateWarningToast: 'Duplicate detected! All pasted lines match history and were skipped.',
    btnToday: 'Today',
    btnYesterday: 'Yesterday',
    btnThisMonth: 'This Month',
    btnPrevMonth: 'Previous Month',
    btnAllDates: 'All',
  },
  km: {
    appName: 'កម្មវិធីតាមដានប្រតិបត្តិការ',
    appSubName: 'ទិន្នន័យរក្សារទុកក្នុងឧបករណ៍របស់អ្នកប្រើប្រាស់រៀងខ្លួន',
    appDesc: 'ទាញយកទិន្នន័យត្រឹមត្រូវភ្លាមៗពីសារ ប្រតិបត្តិការ ធនាគារ ដោយស្វ័យប្រវត្តិកាត់បន្ថយការស្ទួនគ្នា',
    totalTransactions: 'ប្រតិបត្តិការសរុបទាំងអស់',
    totalIncome: 'ចំណូលសរុប',
    totalExpenses: 'ចំណាយសរុប',
    todaysIncome: 'ចំណូលថ្ងៃនេះ',
    todaysInflow: 'លំហូរចូលសាច់ប្រាក់ថ្ងៃនេះ',
    netCashFlow: 'ប្រតិបត្តិការសរុបទាំងអស់',
    recordCount: 'ចំនួនប្រតិបត្តិការ',
    needsReview: 'ត្រូវការពិនិត្យ',
    todayLabel: 'ថ្ងៃនេះ',
    rangeLabel: 'លិទ្ធផលដែរបានស្វែងរក',
    allTimeTotalLabel: 'សរុបក្នុងម៉ាស៊ីន',
    inRangeLabel: 'លិទ្ធផលដែរបានស្វែងរក',
    sourceOthers: 'ផ្សេងៗ',
    clearAllData: 'លប់ទិន្នន័យទាំងអស់',
    placeholderPaste: 'ឧទាហរណ៍៖\n$999.99 paid by KHEAV CHINCHHAY AND HIS WIFE (*666) on Jun 12, 12:26 PM via ABA PAY at Brown Coffee by KCC. Remark: . Trx. ID: 178124197042803, APV: 612744.\n\nឬចុចប៊ូតុង "បង្ហាញគំរូសារ SMS ធនាគារ" ខាងលើដើម្បីចម្លង...',
    parseImport: 'កត់ត្រា',
    searchPlaceholder: 'ស្វែងរកប្រតិបត្តិការតាមឈ្មោះ, លេខយោង, ប្រភព...',
    typeAll: 'គ្រប់ប្រភេទ',
    typeIncome: 'ចំណូល',
    typeExpense: 'ចំណាយ',
    typeUnknown: 'មិនច្បាស់លាស់',
    reviewAll: 'គ្រប់ស្ថានភាព',
    reviewOk: 'ទិន្នន័យធម្មតា',
    reviewFlagged: 'ត្រូវការពិនិត្យ',
    exportCsv: 'នាំចេញជា CSV',
    exportExcel: 'នាំចេញជា Excel',
    exportJson: 'នាំចេញជា JSON',
    printReport: 'បោះពុម្ព',
    thDate: 'កាលបរិច្ឆេទ & ម៉ោង',
    thDetails: 'ហាង / ព័ត៌មានពិពណ៌នា',
    thAmount: 'ទឹកប្រាក់',
    thPayerPayee: 'អ្នកផ្ទេរ / អ្នកទទួល',
    thChannel: 'សេវាកម្ម / ធនាគារ',
    thTrxId: 'លេខយោង / លេខ APV',
    thActions: 'សកម្មភាព',
    btnEdit: 'កែសម្រួល',
    btnDelete: 'លុប',
    noTransactionsYet: 'មិនទាន់មានប្រតិបត្តិការត្រូវបានចុះបញ្ជីនៅឡើយទេ។ សូមសាកល្បងបិទភ្ជាប់សារធនាគារខាងលើ។',
    easySandboxTitle: 'ជំនួយការល្បងទិន្នន័យ៖',
    easySandboxContent: 'មិនទាន់មានសារធនាគារផ្ទាល់ខ្លួនមែនទេ? បើកផ្ទាំង "បង្ហាញគំរូសារ SMS ធនាគារ" ខាងលើ ដើម្បីចម្លងសារគំរូ ABA, Canadia, Acleda មកសាកល្បងបានភ្លាមៗ!',
    toastClearSuccess: 'បានជម្រះទិន្នន័យពីម៉ាស៊ីនដោយជោគជ័យ។',
    toastClearFail: 'ការជម្រះទិន្នន័យបានបរាជ័យ។',
    toastDeleteSuccess: 'បានលុបប្រតិបត្តិការចេញពីប្រព័ន្ធដោយជោគជ័យ។',
    toastDeleteFail: 'លុបប្រតិបត្តិការបរាជ័យ។',
    toastImportSuccess: 'បានកត់ត្រាប្រតិបត្តិការចំនួន {count} ដោយជោគជ័យ។',
    toastImportDuplicate: '(បានរកឃើញស្ទួនចំនួន {count} និងត្រូវបានរំលងដោយស្វ័យប្រវត្តិ)។',
    toastImportReview: '[ចំនួន {count} ត្រូវការពិនិត្យបន្ថែម]',
    modalClearTitle: 'តើអ្នកពិតជាចង់លុបទិន្នន័យទាំងអស់មែនទេ?',
    modalClearWarning: 'រាល់ទិន្នន័យប្រតិបត្តិការទាំងអស់នឹងត្រូវបានលុបចោលជាអចិន្ត្រៃយ៍ពីឧបករណ៍របស់អ្នក ហើយមិនអាចទាញយកមកវិញបានឡើយ!',
    modalClearGoogleSheetsInfo: 'ប្រសិនបើអ្នកបានភ្ជាប់ Google Sheets រួចហើយ ហើយចង់រក្សាទុកទិន្នន័យចាស់នៅក្នុង Sheet បន្ទាប់ពីលុបទិន្នន័យក្នុងប្រព័ន្ធនេះ សូមប្តូរឈ្មោះ Sheet Tab របស់អ្នកនៅក្នុង Google Sheets ជាមុនសិន មុនពេលបញ្ចូលទិន្នន័យថ្មី។ ការលុបទិន្នន័យក្នុងប្រព័ន្ធនេះមិនប៉ះពាល់ដល់ Google Sheet ឡើយ លុះត្រាតែអ្នកបញ្ចូលទិន្នន័យថ្មី និងធ្វើសមកាលកម្ម។',
    modalClearCancel: 'ទេ, រក្សាទុកទិន្នន័យ',
    modalClearConfirm: 'បាទ, លុបចោលទាំងអស់',
    modalPhraseTitle: 'វាយពាក្យសម្គាល់ដើម្បីបញ្ជាក់ការលុប',
    modalPhrasePrompt: 'ដើម្បីលុបទិន្នន័យទាំងអស់ សូមវាយបញ្ចូលពាក្យបញ្ជាក់ខាងក្រោម (អាចប្រើអក្សរធំឬតូចក៏បាន)៖',
    modalPhraseRequiredWord: 'I LOVE BONG CHHAY',
    modalPhrasePlaceholder: 'វាយពាក្យ "I LOVE BONG CHHAY" ទីនេះ...',
    modalPhraseError: 'សូមវាយបញ្ចូលពាក្យ "I LOVE BONG CHHAY" ឱ្យបានត្រឹមត្រូវ។',
    modalPhraseValid: 'ពាក្យត្រូវគ្នាត្រឹមត្រូវ! ចុចប៊ូតុង "បញ្ជាក់" ដើម្បីលុបទិន្នន័យទាំងអស់។',
    modalPhraseConfirmBtn: 'បញ្ជាក់',
    modalPhraseCancelBtn: 'បោះបង់',
    modalDeleteTitle: 'លុបប្រតិបត្តិការនេះ?',
    modalDeleteWarning: 'តើអ្នកពិតជាចង់លុបចោលកំណត់ត្រាប្រតិបត្តិការនេះពីប្រព័ន្ធទិន្នន័យក្នុងឧបករណ៍របស់អ្នកជាអចិន្ត្រៃយ៍មែនទេ?',
    modalDeleteCancel: 'បោះបង់',
    modalDeleteConfirm: 'លុបជាអចិន្ត្រៃយ៍',
    modalEditTitle: 'កែសម្រួលព័ត៌មានលម្អិតប្រតិបត្តិការ',
    labelType: 'ប្រភេទប្រតិបត្តិការ',
    labelAmount: 'ចំនួនទឹកប្រាក់',
    labelCurrency: 'រូបិយប័ណ្ណ',
    labelDate: 'ថ្ងៃខែឆ្នាំ (ឧទាហរណ៍៖ Jun 12)',
    labelTime: 'ម៉ោង (ឧទាហរណ៍៖ 12:26 PM)',
    labelMerchant: 'ឈ្មោះអាជីវករ / ហាង',
    labelPayerPayee: 'ព័ត៌មានអ្នកផ្ទេរ / អ្នកទទួល',
    labelChannel: 'សេវាកម្ម / ធនាគារប្រភព',
    labelTrxId: 'លេខប្រតិបត្តិការ (Trx. ID)',
    labelApv: 'លេខកូដអនុម័ត APV',
    labelRemark: 'សម្គាល់ / ចំណាំ',
    labelRawText: 'អត្ថបទសារដើម',
    labelFlaggedReview: 'ទាមទារការផ្ទៀងផ្ទាត់ឡើងវិញ (ខ្វះទិន្នន័យសំខាន់ៗ)',
    btnSave: 'រក្សាទុកការកែប្រែ',
    btnCancel: 'បោះបង់',
    summaryInflow: 'លំហូរចូលរួចរាល់',
    summaryOutflow: 'លំហូរចេញចំណាយ',
    summarySaved: 'ទិន្នន័យក្នុងប្រព័ន្ធ',
    summaryMissing: 'ខ្វះចំនួនទឹកប្រាក់ឬព័ត៌មាន',
    summaryNetDesc: 'ចំណូលដកចំណាយ',
    filterHeading: 'លក្ខខណ្ឌតម្រងសកម្ម',
    sortByLabel: 'តម្រៀបតាម',
    sortOrderLabel: 'លំដាប់',
    sortDate: 'កាលបរិច្ឆេទ & ម៉ោង',
    sortAmount: 'ចំនួនទឹកប្រាក់',
    sortCreated: 'ថ្ងៃបញ្ចូលទិន្នន័យ',
    orderAsc: 'កើនឡើង',
    orderDesc: 'ចុះក្រោម',
    allSources: 'គ្រប់ប្រភពធនាគារ',
    duplicateText: 'ស្ទួន',
    sampleAlertsTitle: 'គំរូសារ SMS និងការជូនដំណឹងពីធនាគារនៅកម្ពុជា',
    sampleAlertsDesc: 'អ្នកអាចចុចចម្លងសារប្រតិបត្តិការបុកជាភាសាខ្មែរ និងអង់គ្លេសទាំងនេះ ដើម្បីសាកល្បងមុខងារវិភាគទិន្នន័យដោយស្វ័យប្រវត្តិ។',
    clickToCopy: 'ចុចលើប្រអប់នេះដើម្បីចម្លងទិន្នន័យ',
    copiedText: 'បានចម្លងទុកក្នុងក្តារបិទភ្ជាប់ (Clipboard)!',
    howToUseTitle: 'របៀបប្រើប្រាស់ និងសេចក្តីណែនាំអំពីកម្មវិធីវិភាគសារប្រតិបត្តិការ',
    step1: 'ថតចម្លង (Copy) សារតាមដានប្រតិបត្តិការ ឬសារលិខិតជូនដំណឹងទូទាត់ប្រាក់ពីទូរស័ព្ទរបស់អ្នក។',
    step2: 'បិទភ្ជាប់ (Paste) ក្នុងប្រអប់អត្ថបទខាងលើ (អ្នកអាចបញ្ចូលសារច្រើនក្នុងពេលតែមួយដោយដកឃ្លាមួយបន្ទាត់)។',
    step3: 'ចុចប៊ូតុង "កត់ត្រា"។ ប្រព័ន្ធនឹងធ្វើការបំបែកប្រតិបត្តិការស្វែងរកទឹកប្រាក់ USD/KHR, លេខយោង, កូដ APV, និងទប់ស្កាត់ការស្ទួនគ្នា ដោយរក្សាទុកយ៉ាងមានសុវត្ថិភាពក្នុង IndexedDB នៃកម្មវិធីរុករករបស់អ្នក។',
    step4: 'ប្រព័ន្ធវៃឆ្លាតរបស់យើងអាចកំណត់សម្គាល់ប្រភេទ ចំណូល និង ចំណាយ ដោយស្វ័យប្រវត្តពីសារដែលអ្នកបានបិទភ្ជាប់ ហើយអ្នកក៏អាចកត់ត្រាចំណាយ ឬបញ្ជីប្រតិបត្តិការដែលខ្វះចន្លោះដោយដៃផ្ទាល់ផងដែរ។ អ្នកអាចនាំចេញជា CSV/JSON, ធ្វើសមកាលកម្មជាមួយ Google Sheets ឬកែសម្រួលបានគ្រប់ពេល។',
    showSamplesBtn: 'បង្ហាញជំនួយការសារគំរូ',
    hideSamplesBtn: 'លាក់ជំនួយការសារគំរូ',
    filterByLabel: 'ចម្រោះតាម',
    sourceFilterPlaceholder: 'ស្វែងរកប្រភព',
    duplicateWarningToast: 'បានរកឃើញស្ទួន! សារទាំងអស់ដែលអ្នកបញ្ចូលមានរួចរាល់ក្នុងប្រព័ន្ធរួចហើយ។',
    btnToday: 'ថ្ងៃនេះ',
    btnYesterday: 'ម្សិលមិញ',
    btnThisMonth: 'ខែនេះ',
    btnPrevMonth: 'ខែមុន',
    btnAllDates: 'ទាំងអស់',
  }
} as const;

export function getTranslation(lang: Language, key: keyof typeof translations['en'], params?: Record<string, string | number>): string {
  let text = translations[lang][key] || translations['en'][key] || '';
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(new RegExp(`{${k}}`, 'g'), String(v));
    });
  }
  return text;
}
